version: "3"

services:
  reverse-proxy:
    container_name: reverse-proxy
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/reverse-proxy/conf.d:/etc/nginx/conf.d
    links:
      - ghost-blog

  ghost-blog:
    container_name: ghost-blog
    image: ghost:alpine
    restart: always
    ports:
      - 2368:2368
    volumes:
      - ./data/ghost-blog/content:/var/lib/ghost/content
      - ./data/ghost-blog/config.production.json:/var/lib/ghost/config.production.json
    environment:
      - NODE_ENV=production